enyo.depends(
	"WiFi.js",
	"Telephony.js",
	"SystemUpdates.js",
	"SystemUpdates.css",
	"Sound.js",
	"PINNumberPad.js",
	"ScreenLock.js",
	"Licenses.js",
	"LanguageInput.js",
	"DevOptions.js",
	"DevModeService.js",
	"DateTime.js",
	"SearchPreferences.js",
	"About.js",
	"Certificates.js",
	"Settings.js"
);
